id: P1251117F
initial_creation_type: input
source_metadata:
  title: Inscriptions Series
  language: bo
  description: 'A series of inscriptions (byang yig) including verso inscriptions
    (rgyab byang) and recto inscriptions (zhal byang) from thangka paintings and other
    works of art:'
  volume:
    830564312aaf4c95a82a5a44c280e3b4:
      title: Verso Inscription on an Image of the Pure Land of Great Bliss
      parent: Verso Inscriptions
created_at: '2022-03-01T03:59:17.116142'
last_modified_at: '2022-03-01T03:59:17.116145'
